// 环保小兵 · 物品图鉴 — 50 个马来西亚小学常见回收物
// Each item is fully self-contained (no LLM call needed).
// Teachers can edit/add via the admin panel — this is just the seed library.

const BIN_LABELS = {
  aluminum:      { zh: "铝罐",       en: "Aluminum",      color: "#8A9AA8" },
  used_oil:      { zh: "回锅油",     en: "Used oil",      color: "#6F7D3C" },
  newspaper:     { zh: "报纸",       en: "Newspaper",     color: "#D8B35D" },
  metal:         { zh: "铁制品",     en: "Metal",         color: "#737C86" },
  cardboard:     { zh: "纸皮",       en: "Cardboard",     color: "#B07A42" },
  plastic:       { zh: "塑料",       en: "Plastic",       color: "#45A8C7" },
  paper:         { zh: "纸张",       en: "Paper",         color: "#8DB580" },
  ewaste:        { zh: "电子废物",   en: "E-waste",       color: "#9B59B6" },
  hazardous:     { zh: "危险品",     en: "Hazardous",     color: "#C8341A" },
  general_waste: { zh: "普通垃圾",   en: "General waste", color: "#666666" },
  unknown:       { zh: "无法判断",   en: "Unknown",       color: "#999999" },
};

// Group labels for the catalog UI
const CATALOG_GROUPS = [
  { id: "drink",     icon: "🥤", zh: "饮料容器", en: "Drink containers" },
  { id: "package",   icon: "📦", zh: "包装",     en: "Packaging" },
  { id: "paper",     icon: "📄", zh: "纸类",     en: "Paper" },
  { id: "kitchen",   icon: "🍳", zh: "厨房",     en: "Kitchen" },
  { id: "ewaste",    icon: "🔋", zh: "电子",     en: "Electronics" },
  { id: "stationery",icon: "✏️", zh: "文具",     en: "Stationery" },
  { id: "hazard",    icon: "⚠️", zh: "危险",     en: "Hazardous" },
  { id: "other",     icon: "🗑️", zh: "其他",     en: "Other" },
];

const CATALOG_SEED = [
  // ─── DRINK CONTAINERS (8) ─────────────────────────────────
  {
    id: "cat_alu_can", group: "drink", icon: "🥫",
    nameZh: "饮料铝罐", nameEn: "Aluminum drink can",
    binId: "aluminum", isMixed: false,
    materials: ["aluminum"],
    parts: [
      { partZh: "整罐", partEn: "Whole can", binId: "aluminum",
        action: "倒空 → 冲洗 → 压扁 · Empty → rinse → flatten" },
    ],
    starSuggestion: 1,
    studentMsgZh: "把铝罐踩扁可以省好多空间！", studentMsgEn: "Stomp it flat to save space!",
    teacherNoteZh: "示范压扁动作，注意安全（罐口）", teacherNoteEn: "Demo flattening — mind sharp edges",
    tags: ["可乐", "coke", "100plus", "kola", "can", "罐"],
  },
  {
    id: "cat_pet_bottle", group: "drink", icon: "🧴",
    nameZh: "矿泉水/汽水塑料瓶", nameEn: "PET water/soda bottle",
    binId: "plastic", isMixed: true,
    materials: ["PET plastic", "HDPE cap", "paper/plastic label"],
    parts: [
      { partZh: "瓶盖", partEn: "Cap", binId: "plastic",
        action: "拧下来 · Unscrew" },
      { partZh: "瓶身", partEn: "Bottle body", binId: "plastic",
        action: "倒空 → 冲洗 → 压扁 · Empty → rinse → flatten" },
      { partZh: "标签", partEn: "Label", binId: "general_waste",
        action: "撕下来（多数是收缩塑料）· Tear off (mostly shrink plastic)" },
    ],
    starSuggestion: 2,
    studentMsgZh: "3 步！拧盖 → 倒空 → 压扁。", studentMsgEn: "3 steps! Unscrew → empty → flatten.",
    teacherNoteZh: "强调要先冲洗才丢", teacherNoteEn: "Stress rinsing before disposal",
    tags: ["water", "矿泉水", "汽水", "bottle", "pet"],
  },
  {
    id: "cat_tetra_pak", group: "drink", icon: "🥛",
    nameZh: "Tetra Pak 牛奶/果汁盒", nameEn: "Tetra Pak milk/juice carton",
    binId: "paper", isMixed: true,
    materials: ["paper", "plastic cap", "aluminum lining"],
    parts: [
      { partZh: "塑料盖", partEn: "Plastic cap", binId: "plastic",
        action: "拧下盖子 · Unscrew the cap" },
      { partZh: "纸盒身", partEn: "Carton body", binId: "paper",
        action: "倒空 → 冲洗 → 撕开摊平 · Empty → rinse → tear open and flatten" },
      { partZh: "内层铝箔", partEn: "Inner foil", binId: "paper",
        action: "和纸一起回收，不用单独撕 · Recycled with paper, no need to separate" },
    ],
    starSuggestion: 3,
    studentMsgZh: "Tetra Pak 是混合材料！记得拧盖 → 冲洗 → 撕平。",
    studentMsgEn: "Tetra Pak is mixed material! Cap off → rinse → flatten.",
    teacherNoteZh: "经典案例，强调「混合材料要拆开」", teacherNoteEn: "Classic mixed-material teaching example",
    tags: ["tetra", "milk", "牛奶", "果汁", "纸盒"],
  },
  {
    id: "cat_juice_box", group: "drink", icon: "🧃",
    nameZh: "小果汁盒（带吸管）", nameEn: "Small juice box with straw",
    binId: "paper", isMixed: true,
    materials: ["paper", "plastic straw", "plastic wrap"],
    parts: [
      { partZh: "塑料吸管", partEn: "Plastic straw", binId: "plastic",
        action: "拔出来 · Pull out" },
      { partZh: "吸管包装纸", partEn: "Straw wrapper", binId: "general_waste",
        action: "丢一般垃圾 · General waste" },
      { partZh: "盒身", partEn: "Box body", binId: "paper",
        action: "倒空 → 冲洗 → 压扁 · Empty → rinse → flatten" },
    ],
    starSuggestion: 2,
    studentMsgZh: "吸管要拔出来另外丢哦！", studentMsgEn: "Take the straw out separately!",
    teacherNoteZh: "提醒孩子常忘记拔吸管", teacherNoteEn: "Remind kids not to forget the straw",
    tags: ["juice", "果汁", "吸管"],
  },
  {
    id: "cat_plastic_cup", group: "drink", icon: "🥤",
    nameZh: "塑料杯（奶茶杯）", nameEn: "Plastic cup (boba cup)",
    binId: "plastic", isMixed: true,
    materials: ["PP plastic", "plastic lid", "paper straw or plastic straw"],
    parts: [
      { partZh: "盖子", partEn: "Lid", binId: "plastic",
        action: "撕下来 · Remove" },
      { partZh: "杯身", partEn: "Cup body", binId: "plastic",
        action: "倒空 → 冲洗 · Empty → rinse" },
      { partZh: "吸管", partEn: "Straw", binId: "general_waste",
        action: "若是纸吸管不能回收，丢一般垃圾 · Paper straw goes to general waste" },
    ],
    starSuggestion: 2,
    studentMsgZh: "奶茶杯要冲过才能丢哦！", studentMsgEn: "Rinse boba cups before recycling!",
    teacherNoteZh: "提醒甜饮残留招蚂蚁", teacherNoteEn: "Sweet residue attracts ants",
    tags: ["boba", "奶茶", "cup", "杯"],
  },
  {
    id: "cat_glass_bottle", group: "drink", icon: "🍾",
    nameZh: "玻璃瓶", nameEn: "Glass bottle",
    binId: "general_waste", isMixed: true,
    materials: ["glass", "metal cap"],
    parts: [
      { partZh: "金属盖", partEn: "Metal cap", binId: "metal",
        action: "拧下来 · Unscrew" },
      { partZh: "瓶身", partEn: "Glass body", binId: "general_waste",
        action: "冲洗后小心存放（学校无玻璃桶）· Rinse, store carefully (no glass bin at school)" },
    ],
    starSuggestion: 1,
    studentMsgZh: "玻璃要小心！别打破。", studentMsgEn: "Careful with glass — don't break it!",
    teacherNoteZh: "学校没玻璃桶，由老师另外处理", teacherNoteEn: "School has no glass bin; teacher handles separately",
    safetyFlags: ["broken_glass"],
    tags: ["glass", "玻璃", "瓶"],
  },
  {
    id: "cat_hdpe_bottle", group: "drink", icon: "🧴",
    nameZh: "洗洁精/洗发水瓶 (HDPE)", nameEn: "Detergent/shampoo bottle",
    binId: "plastic", isMixed: true,
    materials: ["HDPE plastic", "plastic cap", "plastic label"],
    parts: [
      { partZh: "盖子", partEn: "Cap", binId: "plastic",
        action: "拧下来 · Unscrew" },
      { partZh: "瓶身", partEn: "Bottle body", binId: "plastic",
        action: "倒空 → 冲洗 → 压扁 · Empty → rinse → flatten" },
      { partZh: "标签", partEn: "Label", binId: "plastic",
        action: "保留即可 · Leave attached" },
    ],
    starSuggestion: 1,
    studentMsgZh: "洗洁精瓶冲洗后压扁，超省空间！", studentMsgEn: "Rinse and flatten — saves space!",
    teacherNoteZh: "提醒勿混入仍有液体的瓶", teacherNoteEn: "Don't mix in bottles still containing liquid",
    tags: ["shampoo", "洗发水", "洗洁精", "hdpe"],
  },
  {
    id: "cat_oil_bottle", group: "drink", icon: "🛢️",
    nameZh: "食用油塑料瓶", nameEn: "Cooking oil plastic bottle",
    binId: "plastic", isMixed: true,
    materials: ["PET plastic", "plastic cap"],
    parts: [
      { partZh: "盖子", partEn: "Cap", binId: "plastic",
        action: "拧下来 · Unscrew" },
      { partZh: "瓶身", partEn: "Bottle body", binId: "plastic",
        action: "用热水+洗洁精冲干净 → 压扁 · Wash with hot water + soap → flatten" },
    ],
    starSuggestion: 2,
    studentMsgZh: "油瓶很脏！要好好冲才能丢。", studentMsgEn: "Oil bottles are greasy — wash thoroughly!",
    teacherNoteZh: "油渍会污染整车回收物，必须冲净", teacherNoteEn: "Oil contaminates the whole batch — must be clean",
    tags: ["oil", "油瓶", "minyak"],
  },

  // ─── PACKAGING (7) ─────────────────────────────────
  {
    id: "cat_cardboard_box", group: "package", icon: "📦",
    nameZh: "纸皮箱", nameEn: "Cardboard box",
    binId: "cardboard", isMixed: false,
    materials: ["corrugated cardboard"],
    parts: [
      { partZh: "整箱", partEn: "Whole box", binId: "cardboard",
        action: "拆胶带 → 摊平 → 叠好 · Remove tape → flatten → stack" },
    ],
    starSuggestion: 1,
    studentMsgZh: "摊平就能省好多空间！", studentMsgEn: "Flatten to save tons of space!",
    teacherNoteZh: "教孩子从角线撕开摊平", teacherNoteEn: "Teach tearing along corners to flatten",
    tags: ["cardboard", "纸箱", "box"],
  },
  {
    id: "cat_egg_carton", group: "package", icon: "🥚",
    nameZh: "鸡蛋盒", nameEn: "Egg carton",
    binId: "cardboard", isMixed: false,
    materials: ["molded paper pulp"],
    parts: [
      { partZh: "整盒", partEn: "Whole carton", binId: "cardboard",
        action: "干净就直接丢 · Drop in if clean" },
    ],
    starSuggestion: 1,
    studentMsgZh: "鸡蛋盒是再生纸做的，很环保！", studentMsgEn: "Egg cartons are recycled paper — eco!",
    teacherNoteZh: "若沾蛋液，先擦干净", teacherNoteEn: "Wipe off egg residue first",
    tags: ["egg", "鸡蛋", "carton"],
  },
  {
    id: "cat_paper_cup", group: "package", icon: "🥤",
    nameZh: "纸杯", nameEn: "Paper cup",
    binId: "general_waste", isMixed: true,
    materials: ["paper", "plastic lining"],
    parts: [
      { partZh: "整杯", partEn: "Whole cup", binId: "general_waste",
        action: "内层有塑料膜，多数当一般垃圾 · Plastic-lined, usually general waste" },
    ],
    starSuggestion: 1,
    studentMsgZh: "纸杯其实内层有塑料，不是纯纸哦！", studentMsgEn: "Paper cups have plastic inside — not pure paper!",
    teacherNoteZh: "教育「看似纸，实则混合」", teacherNoteEn: "Teach 'looks like paper but is actually mixed'",
    tags: ["cup", "纸杯"],
  },
  {
    id: "cat_can_food", group: "package", icon: "🥫",
    nameZh: "食品罐头 (沙丁鱼/午餐肉)", nameEn: "Canned food (sardine/spam)",
    binId: "metal", isMixed: true,
    materials: ["tin-plated steel", "paper label"],
    parts: [
      { partZh: "纸标签", partEn: "Paper label", binId: "paper",
        action: "撕下来 · Tear off" },
      { partZh: "金属罐", partEn: "Metal can", binId: "metal",
        action: "倒空 → 冲洗 → 压扁（小心边缘）· Empty → rinse → flatten (mind edges)" },
    ],
    starSuggestion: 2,
    studentMsgZh: "撕下标签，冲干净，压扁！", studentMsgEn: "Tear label, rinse, flatten!",
    teacherNoteZh: "罐口锋利，提醒孩子小心", teacherNoteEn: "Sharp edges — warn kids",
    safetyFlags: ["sharp"],
    tags: ["sardine", "罐头", "canned"],
  },
  {
    id: "cat_milk_powder_tin", group: "package", icon: "🥫",
    nameZh: "奶粉罐", nameEn: "Milk powder tin",
    binId: "metal", isMixed: true,
    materials: ["tin-plated steel", "plastic lid", "paper label"],
    parts: [
      { partZh: "塑料盖", partEn: "Plastic lid", binId: "plastic",
        action: "取下来 · Remove" },
      { partZh: "纸标签", partEn: "Paper label", binId: "paper",
        action: "撕下来 · Tear off" },
      { partZh: "金属罐", partEn: "Metal tin", binId: "metal",
        action: "擦干净 → 投入铁制品 · Wipe clean → drop in metal bin" },
    ],
    starSuggestion: 2,
    studentMsgZh: "三层包装！每层都要分开。", studentMsgEn: "3-layer packaging! Separate each layer.",
    teacherNoteZh: "示范取盖、撕标签", teacherNoteEn: "Demo lid removal and label peeling",
    tags: ["milk powder", "奶粉罐"],
  },
  {
    id: "cat_plastic_bag", group: "package", icon: "🛍️",
    nameZh: "塑料袋", nameEn: "Plastic bag",
    binId: "plastic", isMixed: false,
    materials: ["LDPE plastic"],
    parts: [
      { partZh: "整袋", partEn: "Whole bag", binId: "plastic",
        action: "干净就折叠收好 · Fold neatly if clean" },
    ],
    starSuggestion: 1,
    studentMsgZh: "塑料袋可以重复用很多次！", studentMsgEn: "Plastic bags can be reused many times!",
    teacherNoteZh: "鼓励重用而非回收", teacherNoteEn: "Encourage reuse over recycling",
    tags: ["plastic bag", "塑料袋", "beg"],
  },
  {
    id: "cat_styrofoam", group: "package", icon: "📦",
    nameZh: "保丽龙/泡沫盒", nameEn: "Styrofoam container",
    binId: "general_waste", isMixed: false,
    materials: ["polystyrene foam"],
    parts: [
      { partZh: "整盒", partEn: "Whole box", binId: "general_waste",
        action: "马来西亚通常不回收 → 普通垃圾 · Usually not recycled in MY → general waste" },
    ],
    starSuggestion: 0,
    studentMsgZh: "保丽龙很难回收，下次自带饭盒！", studentMsgEn: "Foam is hard to recycle — bring your own box!",
    teacherNoteZh: "教育减少使用一次性保丽龙", teacherNoteEn: "Teach reducing single-use foam",
    tags: ["foam", "styrofoam", "保丽龙", "饭盒"],
  },

  // ─── PAPER (10) ─────────────────────────────────
  {
    id: "cat_newspaper", group: "paper", icon: "📰",
    nameZh: "报纸", nameEn: "Newspaper",
    binId: "newspaper", isMixed: false,
    materials: ["newsprint paper"],
    parts: [
      { partZh: "整叠", partEn: "Whole stack", binId: "newspaper",
        action: "叠整齐捆好 · Stack and tie neatly" },
    ],
    starSuggestion: 1,
    studentMsgZh: "报纸要叠整齐！", studentMsgEn: "Stack newspapers neatly!",
    teacherNoteZh: "演示用绳子捆扎", teacherNoteEn: "Demo tying with string",
    tags: ["newspaper", "报纸", "akhbar"],
  },
  {
    id: "cat_magazine", group: "paper", icon: "📖",
    nameZh: "杂志", nameEn: "Magazine",
    binId: "paper", isMixed: false,
    materials: ["coated paper"],
    parts: [
      { partZh: "整本", partEn: "Whole magazine", binId: "paper",
        action: "直接投入纸张桶 · Drop into paper bin" },
    ],
    starSuggestion: 1,
    studentMsgZh: "杂志和报纸不一样桶哦！", studentMsgEn: "Magazines and newspapers go in different bins!",
    teacherNoteZh: "光面纸≠新闻纸", teacherNoteEn: "Glossy ≠ newsprint",
    tags: ["magazine", "杂志"],
  },
  {
    id: "cat_textbook", group: "paper", icon: "📚",
    nameZh: "课本/书本", nameEn: "Textbook / Book",
    binId: "paper", isMixed: true,
    materials: ["paper", "hard cover"],
    parts: [
      { partZh: "硬封皮", partEn: "Hard cover", binId: "general_waste",
        action: "拆掉硬封皮 · Tear off hard cover" },
      { partZh: "内页", partEn: "Inner pages", binId: "paper",
        action: "投入纸张桶 · Drop into paper bin" },
    ],
    starSuggestion: 2,
    studentMsgZh: "可以的话先转送学弟妹！", studentMsgEn: "Pass it on to juniors if possible!",
    teacherNoteZh: "优先鼓励转赠而非回收", teacherNoteEn: "Encourage donation first, recycling second",
    tags: ["book", "课本", "buku"],
  },
  {
    id: "cat_notebook", group: "paper", icon: "📓",
    nameZh: "笔记本", nameEn: "Notebook",
    binId: "paper", isMixed: true,
    materials: ["paper", "metal spiral or staples"],
    parts: [
      { partZh: "金属线圈/钉书钉", partEn: "Spiral / staples", binId: "metal",
        action: "拆下来 · Remove" },
      { partZh: "纸页", partEn: "Paper pages", binId: "paper",
        action: "投入纸张桶 · Drop into paper bin" },
    ],
    starSuggestion: 2,
    studentMsgZh: "线圈是金属，要拆掉哦！", studentMsgEn: "Spiral is metal — remove it!",
    teacherNoteZh: "提醒未写完页面可剪下来再用", teacherNoteEn: "Unused pages can be cut out for reuse",
    tags: ["notebook", "笔记本"],
  },
  {
    id: "cat_envelope", group: "paper", icon: "✉️",
    nameZh: "信封", nameEn: "Envelope",
    binId: "paper", isMixed: false,
    materials: ["paper"],
    parts: [
      { partZh: "整个", partEn: "Whole envelope", binId: "paper",
        action: "投入纸张桶 · Drop in paper bin" },
    ],
    starSuggestion: 1,
    studentMsgZh: "塑料窗的信封要先撕掉窗哦。", studentMsgEn: "Tear off the plastic window first!",
    teacherNoteZh: "示范撕除塑料窗", teacherNoteEn: "Demo removing plastic window",
    tags: ["envelope", "信封"],
  },
  {
    id: "cat_paper_a4", group: "paper", icon: "📄",
    nameZh: "A4 打印纸/作业纸", nameEn: "A4 printer/worksheet paper",
    binId: "paper", isMixed: false,
    materials: ["paper"],
    parts: [
      { partZh: "整叠", partEn: "Whole stack", binId: "paper",
        action: "整理后投入 · Stack and drop in" },
    ],
    starSuggestion: 1,
    studentMsgZh: "用单面，背面可以再用！", studentMsgEn: "Use one side, reuse the back!",
    teacherNoteZh: "鼓励双面使用", teacherNoteEn: "Encourage double-sided use",
    tags: ["a4", "paper", "纸"],
  },
  {
    id: "cat_receipt", group: "paper", icon: "🧾",
    nameZh: "收据 (热敏纸)", nameEn: "Receipt (thermal paper)",
    binId: "general_waste", isMixed: false,
    materials: ["thermal paper (BPA-coated)"],
    parts: [
      { partZh: "整张", partEn: "Whole receipt", binId: "general_waste",
        action: "不可回收（含化学涂层）· Not recyclable (chemical coating)" },
    ],
    starSuggestion: 0,
    studentMsgZh: "收据虽然看起来像纸，但不能回收！", studentMsgEn: "Receipts look like paper but cannot be recycled!",
    teacherNoteZh: "热敏纸含 BPA，污染回收纸浆", teacherNoteEn: "Thermal paper has BPA — contaminates pulp",
    tags: ["receipt", "收据"],
  },
  {
    id: "cat_tissue", group: "paper", icon: "🧻",
    nameZh: "卫生纸/餐巾纸", nameEn: "Tissue / napkin",
    binId: "general_waste", isMixed: false,
    materials: ["paper (used)"],
    parts: [
      { partZh: "整张", partEn: "Whole tissue", binId: "general_waste",
        action: "用过的不能回收 · Used tissue can't be recycled" },
    ],
    starSuggestion: 0,
    studentMsgZh: "用过的纸巾不能回收哦！", studentMsgEn: "Used tissues can't be recycled!",
    teacherNoteZh: "纤维太短 + 已污染", teacherNoteEn: "Short fibers + already soiled",
    tags: ["tissue", "卫生纸", "napkin"],
  },
  {
    id: "cat_pizza_box", group: "paper", icon: "🍕",
    nameZh: "披萨盒", nameEn: "Pizza box",
    binId: "general_waste", isMixed: false,
    materials: ["cardboard (oil-contaminated)"],
    parts: [
      { partZh: "整盒", partEn: "Whole box", binId: "general_waste",
        action: "沾油的部分不能回收 · Oily parts cannot be recycled" },
    ],
    starSuggestion: 0,
    studentMsgZh: "披萨盒沾油，不能回收哦！", studentMsgEn: "Pizza boxes are too oily to recycle!",
    teacherNoteZh: "若上盖干净，可剪下来回收", teacherNoteEn: "Clean top can be cut off and recycled",
    tags: ["pizza", "披萨"],
  },
  {
    id: "cat_color_paper", group: "paper", icon: "🎨",
    nameZh: "彩色包装纸/卡纸", nameEn: "Colored wrap/card paper",
    binId: "paper", isMixed: false,
    materials: ["dyed paper"],
    parts: [
      { partZh: "整张", partEn: "Whole sheet", binId: "paper",
        action: "干净就投入纸张桶 · Drop in paper bin if clean" },
    ],
    starSuggestion: 1,
    studentMsgZh: "金箔/亮粉的包装纸不能回收哦！", studentMsgEn: "Foil / glitter paper cannot be recycled!",
    teacherNoteZh: "金属涂层的不能回收", teacherNoteEn: "Metallic-coated cannot be recycled",
    tags: ["wrap", "包装", "卡纸"],
  },

  // ─── KITCHEN (5) ─────────────────────────────────
  {
    id: "cat_used_oil", group: "kitchen", icon: "🛢️",
    nameZh: "回锅油 (食用油)", nameEn: "Used cooking oil",
    binId: "used_oil", isMixed: false,
    materials: ["used vegetable oil"],
    parts: [
      { partZh: "倒入回收桶", partEn: "Pour into used-oil bin", binId: "used_oil",
        action: "用瓶子装好 → 倒入回锅油桶 · Bottle it → pour into used-oil bin" },
    ],
    starSuggestion: 3,
    studentMsgZh: "回锅油可以做肥皂和生物柴油！", studentMsgEn: "Used oil can become soap or biodiesel!",
    teacherNoteZh: "学校最有价值的回收物之一（RM3.40/kg）", teacherNoteEn: "One of the highest-value recyclables at school",
    tags: ["oil", "回锅油", "minyak"],
  },
  {
    id: "cat_food_waste", group: "kitchen", icon: "🍎",
    nameZh: "食物残渣/果皮", nameEn: "Food scraps / peels",
    binId: "general_waste", isMixed: false,
    materials: ["organic"],
    parts: [
      { partZh: "整份", partEn: "All scraps", binId: "general_waste",
        action: "暂无堆肥桶 → 一般垃圾（或带回家堆肥）· No compost bin → general waste (or compost at home)" },
    ],
    starSuggestion: 1,
    studentMsgZh: "如果有堆肥桶最好！", studentMsgEn: "Best if there's a compost bin!",
    teacherNoteZh: "可以是未来项目：校园堆肥", teacherNoteEn: "Possible future project: campus composting",
    tags: ["food", "果皮", "残渣"],
  },
  {
    id: "cat_teabag", group: "kitchen", icon: "🍵",
    nameZh: "茶包", nameEn: "Tea bag",
    binId: "general_waste", isMixed: true,
    materials: ["paper or plastic mesh", "tea leaves"],
    parts: [
      { partZh: "整包（含线和标签）", partEn: "Whole bag", binId: "general_waste",
        action: "湿的茶包当一般垃圾 · Wet tea bag → general waste" },
    ],
    starSuggestion: 0,
    studentMsgZh: "湿垃圾不能回收哦！", studentMsgEn: "Wet items can't be recycled!",
    teacherNoteZh: "可以是堆肥项目素材", teacherNoteEn: "Good compost material",
    tags: ["tea", "茶包"],
  },
  {
    id: "cat_plastic_lunchbox", group: "kitchen", icon: "🍱",
    nameZh: "塑料便当盒", nameEn: "Plastic lunchbox",
    binId: "plastic", isMixed: true,
    materials: ["PP plastic", "PP lid"],
    parts: [
      { partZh: "盖子", partEn: "Lid", binId: "plastic",
        action: "分开 · Separate" },
      { partZh: "盒身", partEn: "Box body", binId: "plastic",
        action: "冲洗 · Rinse" },
    ],
    starSuggestion: 1,
    studentMsgZh: "尽量重用，不要丢！", studentMsgEn: "Reuse first, recycle last!",
    teacherNoteZh: "鼓励学生自带便当盒", teacherNoteEn: "Encourage bringing reusable lunchboxes",
    tags: ["lunchbox", "便当盒"],
  },
  {
    id: "cat_straw", group: "kitchen", icon: "🥤",
    nameZh: "吸管", nameEn: "Straw",
    binId: "general_waste", isMixed: false,
    materials: ["PP plastic (too small to recycle)"],
    parts: [
      { partZh: "整支", partEn: "Whole straw", binId: "general_waste",
        action: "太小，机器分不出来 → 一般垃圾 · Too small for sorting → general waste" },
    ],
    starSuggestion: 0,
    studentMsgZh: "吸管太小不能回收，下次拒绝吸管！", studentMsgEn: "Straws are too small — refuse next time!",
    teacherNoteZh: "教育「拒绝 Refuse」是 5R 第一步", teacherNoteEn: "Teach Refuse — the first R in 5Rs",
    tags: ["straw", "吸管"],
  },

  // ─── E-WASTE (8) ─────────────────────────────────
  {
    id: "cat_aa_battery", group: "ewaste", icon: "🔋",
    nameZh: "AA/AAA 电池", nameEn: "AA/AAA battery",
    binId: "ewaste", isMixed: false,
    materials: ["alkaline / lithium"],
    parts: [
      { partZh: "整颗", partEn: "Whole battery", binId: "ewaste",
        action: "投入电子废物桶（绝对不能进普通垃圾！）· E-waste bin only — NEVER general waste!" },
    ],
    starSuggestion: 3,
    studentMsgZh: "电池绝对不能丢普通垃圾！", studentMsgEn: "NEVER throw batteries in general waste!",
    teacherNoteZh: "强调电池漏液会污染土壤水源", teacherNoteEn: "Stress that leaks contaminate soil and water",
    safetyFlags: ["battery"],
    tags: ["battery", "电池", "bateri"],
  },
  {
    id: "cat_button_battery", group: "ewaste", icon: "🪙",
    nameZh: "钮扣电池", nameEn: "Button battery",
    binId: "ewaste", isMixed: false,
    materials: ["lithium / mercury"],
    parts: [
      { partZh: "整颗", partEn: "Whole battery", binId: "ewaste",
        action: "投入电子废物桶，远离小朋友 · E-waste bin only, keep away from kids" },
    ],
    starSuggestion: 3,
    studentMsgZh: "钮扣电池超危险！小朋友千万别吞。", studentMsgEn: "Button batteries are dangerous — never swallow!",
    teacherNoteZh: "误吞极度危险，要严肃讲", teacherNoteEn: "Swallowing is life-threatening — emphasize seriously",
    safetyFlags: ["battery"],
    tags: ["button battery", "钮扣电池"],
  },
  {
    id: "cat_phone", group: "ewaste", icon: "📱",
    nameZh: "旧手机", nameEn: "Old phone",
    binId: "ewaste", isMixed: false,
    materials: ["mixed electronics"],
    parts: [
      { partZh: "整支", partEn: "Whole phone", binId: "ewaste",
        action: "去除 SIM 卡 → 投入电子废物 · Remove SIM → e-waste bin" },
    ],
    starSuggestion: 3,
    studentMsgZh: "里面有很多稀有金属！", studentMsgEn: "Contains rare metals — worth recycling!",
    teacherNoteZh: "提醒数据清除", teacherNoteEn: "Remind to wipe data first",
    tags: ["phone", "手机", "telefon"],
  },
  {
    id: "cat_cable", group: "ewaste", icon: "🔌",
    nameZh: "充电线/USB 线", nameEn: "Cable / USB cord",
    binId: "ewaste", isMixed: false,
    materials: ["copper", "PVC plastic"],
    parts: [
      { partZh: "整条", partEn: "Whole cable", binId: "ewaste",
        action: "投入电子废物 · E-waste bin" },
    ],
    starSuggestion: 2,
    studentMsgZh: "里面有铜线，可以回收！", studentMsgEn: "Has copper inside — recyclable!",
    teacherNoteZh: "铜是高价值回收材料", teacherNoteEn: "Copper is high-value",
    tags: ["cable", "充电线", "usb"],
  },
  {
    id: "cat_earphones", group: "ewaste", icon: "🎧",
    nameZh: "耳机", nameEn: "Earphones",
    binId: "ewaste", isMixed: false,
    materials: ["mixed electronics"],
    parts: [
      { partZh: "整副", partEn: "Whole pair", binId: "ewaste",
        action: "投入电子废物 · E-waste bin" },
    ],
    starSuggestion: 2,
    studentMsgZh: "可以先试着修理！", studentMsgEn: "Try repairing first!",
    teacherNoteZh: "提倡修补文化 Repair Culture", teacherNoteEn: "Promote repair culture",
    tags: ["earphone", "耳机"],
  },
  {
    id: "cat_cd", group: "ewaste", icon: "💿",
    nameZh: "CD/DVD 光盘", nameEn: "CD/DVD disc",
    binId: "ewaste", isMixed: true,
    materials: ["polycarbonate plastic", "aluminum layer"],
    parts: [
      { partZh: "整片", partEn: "Whole disc", binId: "ewaste",
        action: "投入电子废物（含金属层）· E-waste (has metal layer)" },
    ],
    starSuggestion: 2,
    studentMsgZh: "光盘内层有金属哦！", studentMsgEn: "Discs have metal layers inside!",
    teacherNoteZh: "或可剪成 DIY 装饰", teacherNoteEn: "Or use for DIY crafts",
    tags: ["cd", "dvd", "光盘"],
  },
  {
    id: "cat_led_bulb", group: "ewaste", icon: "💡",
    nameZh: "LED 灯泡", nameEn: "LED light bulb",
    binId: "ewaste", isMixed: false,
    materials: ["electronics", "glass"],
    parts: [
      { partZh: "整颗", partEn: "Whole bulb", binId: "ewaste",
        action: "小心轻放 → 电子废物 · Handle carefully → e-waste" },
    ],
    starSuggestion: 2,
    studentMsgZh: "灯泡里有电路板！", studentMsgEn: "Bulbs have circuit boards inside!",
    teacherNoteZh: "破损时小心玻璃", teacherNoteEn: "Mind glass shards if broken",
    safetyFlags: ["broken_glass"],
    tags: ["led", "灯泡", "lampu"],
  },
  {
    id: "cat_keyboard", group: "ewaste", icon: "⌨️",
    nameZh: "键盘/鼠标", nameEn: "Keyboard / Mouse",
    binId: "ewaste", isMixed: false,
    materials: ["plastic", "electronics"],
    parts: [
      { partZh: "整件", partEn: "Whole device", binId: "ewaste",
        action: "投入电子废物 · E-waste bin" },
    ],
    starSuggestion: 2,
    studentMsgZh: "电脑用品不能进普通垃圾！", studentMsgEn: "Computer items don't go to general waste!",
    teacherNoteZh: "提倡先修后弃", teacherNoteEn: "Repair before discard",
    tags: ["keyboard", "mouse", "键盘", "鼠标"],
  },

  // ─── STATIONERY (5) ─────────────────────────────────
  {
    id: "cat_pen", group: "stationery", icon: "🖊️",
    nameZh: "原子笔/塑料笔", nameEn: "Ballpoint / plastic pen",
    binId: "general_waste", isMixed: true,
    materials: ["plastic body", "metal tip", "ink tube"],
    parts: [
      { partZh: "整支", partEn: "Whole pen", binId: "general_waste",
        action: "太小不易拆 → 一般垃圾 · Too small to disassemble → general waste" },
    ],
    starSuggestion: 0,
    studentMsgZh: "用完笔再丢，不要还有墨水！", studentMsgEn: "Use up the ink before discarding!",
    teacherNoteZh: "可以发起「用完一支笔」活动", teacherNoteEn: "Try 'finish a pen' challenge",
    tags: ["pen", "笔", "原子笔"],
  },
  {
    id: "cat_pencil", group: "stationery", icon: "✏️",
    nameZh: "铅笔（用完）", nameEn: "Pencil (stub)",
    binId: "general_waste", isMixed: false,
    materials: ["wood", "graphite"],
    parts: [
      { partZh: "整支", partEn: "Whole pencil", binId: "general_waste",
        action: "用到最短再丢 · Use until tiny" },
    ],
    starSuggestion: 1,
    studentMsgZh: "铅笔短了用接笔器！", studentMsgEn: "Use a pencil extender when short!",
    teacherNoteZh: "示范使用接笔器", teacherNoteEn: "Demo pencil extenders",
    tags: ["pencil", "铅笔"],
  },
  {
    id: "cat_marker", group: "stationery", icon: "🖍️",
    nameZh: "白板笔/记号笔", nameEn: "Marker pen",
    binId: "hazardous", isMixed: false,
    materials: ["plastic", "ink (solvent-based)"],
    parts: [
      { partZh: "整支", partEn: "Whole marker", binId: "hazardous",
        action: "含化学溶剂 → 危险品桶 · Contains solvent → hazardous bin" },
    ],
    starSuggestion: 1,
    studentMsgZh: "白板笔里的墨水有化学品！", studentMsgEn: "Marker ink has chemicals!",
    teacherNoteZh: "若学校无危险品桶，集中存放后送回收商", teacherNoteEn: "If no hazardous bin, collect for proper disposal",
    safetyFlags: ["chemical"],
    tags: ["marker", "白板笔"],
  },
  {
    id: "cat_plastic_folder", group: "stationery", icon: "🗂️",
    nameZh: "塑料文件夹", nameEn: "Plastic folder",
    binId: "plastic", isMixed: false,
    materials: ["PP plastic"],
    parts: [
      { partZh: "整本", partEn: "Whole folder", binId: "plastic",
        action: "去掉里面的纸 → 投塑料 · Remove papers → plastic bin" },
    ],
    starSuggestion: 1,
    studentMsgZh: "尽量传给下一届！", studentMsgEn: "Pass on to next year's students!",
    teacherNoteZh: "鼓励文件夹传承", teacherNoteEn: "Encourage handing folders down",
    tags: ["folder", "文件夹"],
  },
  {
    id: "cat_eraser", group: "stationery", icon: "🧽",
    nameZh: "橡皮擦（用完）", nameEn: "Eraser (used up)",
    binId: "general_waste", isMixed: false,
    materials: ["synthetic rubber"],
    parts: [
      { partZh: "整块", partEn: "Whole eraser", binId: "general_waste",
        action: "合成橡胶不能回收 → 一般垃圾 · Synthetic rubber → general waste" },
    ],
    starSuggestion: 0,
    studentMsgZh: "用到最小再丢哦！", studentMsgEn: "Use until tiny!",
    teacherNoteZh: "鼓励物尽其用", teacherNoteEn: "Encourage full use",
    tags: ["eraser", "橡皮"],
  },

  // ─── HAZARD (4) ─────────────────────────────────
  {
    id: "cat_aerosol", group: "hazard", icon: "🧴",
    nameZh: "喷雾罐 (杀虫剂/发胶)", nameEn: "Aerosol spray can",
    binId: "hazardous", isMixed: false,
    materials: ["pressurized aluminum/steel"],
    parts: [
      { partZh: "整罐", partEn: "Whole can", binId: "hazardous",
        action: "完全用完 → 危险品桶（千万别压扁!）· Empty completely → hazardous bin (DON'T crush!)" },
    ],
    starSuggestion: 2,
    studentMsgZh: "喷雾罐绝对不能压扁，会爆炸！", studentMsgEn: "NEVER crush aerosol cans — they explode!",
    teacherNoteZh: "强调安全：压扁可能引爆", teacherNoteEn: "Stress safety: crushing can cause explosion",
    safetyFlags: ["chemical"],
    tags: ["aerosol", "喷雾", "杀虫剂"],
  },
  {
    id: "cat_paint", group: "hazard", icon: "🎨",
    nameZh: "油漆罐", nameEn: "Paint can",
    binId: "hazardous", isMixed: false,
    materials: ["metal", "paint residue"],
    parts: [
      { partZh: "整罐", partEn: "Whole can", binId: "hazardous",
        action: "需专业处理 · Needs professional disposal" },
    ],
    starSuggestion: 2,
    studentMsgZh: "油漆有化学品，不能乱丢！", studentMsgEn: "Paint has chemicals — never just throw away!",
    teacherNoteZh: "联系市议会有害废物收集", teacherNoteEn: "Contact municipal hazardous waste service",
    safetyFlags: ["chemical"],
    tags: ["paint", "油漆"],
  },
  {
    id: "cat_fluorescent", group: "hazard", icon: "💡",
    nameZh: "荧光灯管 (含汞)", nameEn: "Fluorescent tube (mercury)",
    binId: "hazardous", isMixed: false,
    materials: ["glass", "mercury vapor"],
    parts: [
      { partZh: "整支", partEn: "Whole tube", binId: "hazardous",
        action: "小心搬运，绝对不要打破 · Handle carefully, NEVER break" },
    ],
    starSuggestion: 3,
    studentMsgZh: "荧光灯打破会释放有毒汞气！", studentMsgEn: "Broken tubes release toxic mercury!",
    teacherNoteZh: "必须由成人处理", teacherNoteEn: "Adult-only handling",
    safetyFlags: ["broken_glass", "chemical"],
    tags: ["fluorescent", "荧光灯", "汞"],
  },
  {
    id: "cat_medicine", group: "hazard", icon: "💊",
    nameZh: "过期药品", nameEn: "Expired medicine",
    binId: "hazardous", isMixed: false,
    materials: ["pharmaceutical"],
    parts: [
      { partZh: "全部", partEn: "All medicine", binId: "hazardous",
        action: "送回药房，不要冲马桶！· Return to pharmacy, don't flush!" },
    ],
    starSuggestion: 3,
    studentMsgZh: "过期药要带回药房，不能乱丢！", studentMsgEn: "Return expired meds to pharmacy!",
    teacherNoteZh: "马来西亚药房有回收点", teacherNoteEn: "Malaysian pharmacies accept returns",
    safetyFlags: ["medical_waste"],
    tags: ["medicine", "药品", "ubat"],
  },

  // ─── OTHER (3) ─────────────────────────────────
  {
    id: "cat_shoes", group: "other", icon: "👟",
    nameZh: "旧鞋", nameEn: "Old shoes",
    binId: "general_waste", isMixed: true,
    materials: ["rubber", "fabric", "plastic"],
    parts: [
      { partZh: "整双", partEn: "Whole pair", binId: "general_waste",
        action: "若还能穿 → 捐赠；不能穿 → 一般垃圾 · Wearable → donate; broken → general waste" },
    ],
    starSuggestion: 2,
    studentMsgZh: "好的旧鞋可以捐给有需要的小朋友！", studentMsgEn: "Good shoes can be donated to others in need!",
    teacherNoteZh: "学校可以组织捐鞋活动", teacherNoteEn: "Organise a shoe-donation drive",
    tags: ["shoes", "鞋"],
  },
  {
    id: "cat_clothes", group: "other", icon: "👕",
    nameZh: "旧校服/衣物", nameEn: "Old uniform / clothes",
    binId: "general_waste", isMixed: false,
    materials: ["fabric"],
    parts: [
      { partZh: "整件", partEn: "Whole garment", binId: "general_waste",
        action: "完好 → 捐赠；破损 → 当抹布 · Good → donate; broken → use as rag" },
    ],
    starSuggestion: 2,
    studentMsgZh: "好的校服传给学弟妹！", studentMsgEn: "Pass uniforms to juniors!",
    teacherNoteZh: "校服传承是很好的传统", teacherNoteEn: "Uniform handing-down is great tradition",
    tags: ["clothes", "校服", "uniform"],
  },
  {
    id: "cat_unknown", group: "other", icon: "❓",
    nameZh: "看不出是什么", nameEn: "Not sure what it is",
    binId: "unknown", isMixed: false,
    materials: ["unknown"],
    parts: [
      { partZh: "暂存", partEn: "Set aside", binId: "unknown",
        action: "问老师，或用 🤖 AI 帮你认 · Ask teacher, or use 🤖 AI scan" },
    ],
    starSuggestion: 0,
    studentMsgZh: "不确定就问老师！", studentMsgEn: "When in doubt, ask teacher!",
    teacherNoteZh: "鼓励学生「不确定就问」", teacherNoteEn: "Praise 'when unsure, ask'",
    tags: ["unknown", "未知"],
  },
];

window.EcoCatalog = {
  BIN_LABELS,
  CATALOG_GROUPS,
  SEED: CATALOG_SEED,
};
